# ComplexHeatmap Template Generator
# Interactive script to help generate custom heatmap code

cat("========================================\n")
cat("ComplexHeatmap Template Generator\n")
cat("========================================\n\n")

# Function to get yes/no input
get_yes_no <- function(prompt) {
    cat(prompt, "(y/n): ")
    response <- tolower(trimws(readLines(con = stdin(), n = 1)))
    return(response == "y" || response == "yes")
}

# Function to get numeric input
get_number <- function(prompt, default = NULL) {
    if (!is.null(default)) {
        cat(sprintf("%s (default: %s): ", prompt, default))
    } else {
        cat(prompt, ": ")
    }
    response <- trimws(readLines(con = stdin(), n = 1))
    if (response == "" && !is.null(default)) {
        return(default)
    }
    return(as.numeric(response))
}

# Function to get text input
get_text <- function(prompt, default = NULL) {
    if (!is.null(default)) {
        cat(sprintf("%s (default: %s): ", prompt, default))
    } else {
        cat(prompt, ": ")
    }
    response <- trimws(readLines(con = stdin(), n = 1))
    if (response == "" && !is.null(default)) {
        return(default)
    }
    return(response)
}

cat("This script will help you generate a custom ComplexHeatmap template.\n\n")

# ==============================================================================
# 1. Data Type
# ==============================================================================
cat("Step 1: Data Type\n")
cat("-----------------\n")
cat("1. Gene expression\n")
cat("2. Correlation matrix\n")
cat("3. Generic numeric matrix\n")
cat("4. OncoPrint (alterations)\n")
data_type <- get_number("Select data type (1-4)", 1)
cat("\n")

# ==============================================================================
# 2. Dimensions
# ==============================================================================
cat("Step 2: Matrix Dimensions\n")
cat("-------------------------\n")
n_rows <- get_number("Number of rows (genes/features)", 50)
n_cols <- get_number("Number of columns (samples)", 20)
cat("\n")

# ==============================================================================
# 3. Clustering
# ==============================================================================
cat("Step 3: Clustering Options\n")
cat("--------------------------\n")
cluster_rows <- get_yes_no("Cluster rows?")
cluster_cols <- get_yes_no("Cluster columns?")

if (cluster_rows || cluster_cols) {
    cat("\nDistance metrics:\n")
    cat("  1. euclidean\n")
    cat("  2. pearson\n")
    cat("  3. spearman\n")
    dist_choice <- get_number("Select distance (1-3)", 1)
    distance <- c("euclidean", "pearson", "spearman")[dist_choice]
    
    cat("\nLinkage methods:\n")
    cat("  1. complete\n")
    cat("  2. ward.D2\n")
    cat("  3. average\n")
    method_choice <- get_number("Select method (1-3)", 1)
    method <- c("complete", "ward.D2", "average")[method_choice]
} else {
    distance <- "euclidean"
    method <- "complete"
}
cat("\n")

# ==============================================================================
# 4. Annotations
# ==============================================================================
cat("Step 4: Annotations\n")
cat("-------------------\n")
add_col_anno <- get_yes_no("Add column annotations?")
if (add_col_anno) {
    n_col_anno <- get_number("Number of column annotation tracks", 2)
} else {
    n_col_anno <- 0
}

add_row_anno <- get_yes_no("Add row annotations?")
if (add_row_anno) {
    n_row_anno <- get_number("Number of row annotation tracks", 1)
} else {
    n_row_anno <- 0
}
cat("\n")

# ==============================================================================
# 5. Color Scheme
# ==============================================================================
cat("Step 5: Color Scheme\n")
cat("--------------------\n")
cat("Color schemes:\n")
cat("  1. Blue-White-Red (diverging)\n")
cat("  2. Green-Black-Red (expression)\n")
cat("  3. Viridis (sequential)\n")
cat("  4. Custom\n")
color_choice <- get_number("Select color scheme (1-4)", 1)
cat("\n")

# ==============================================================================
# 6. Output Format
# ==============================================================================
cat("Step 6: Output\n")
cat("--------------\n")
output_name <- get_text("Output filename (without extension)", "my_heatmap")
cat("\n")

# ==============================================================================
# Generate Code
# ==============================================================================
cat("Generating template code...\n\n")

code <- paste0("# ComplexHeatmap Template
# Generated by template_generator.R

library(ComplexHeatmap)
library(circlize)

# Set seed for reproducibility
set.seed(123)

# ==============================================================================
# 1. LOAD/GENERATE DATA
# ==============================================================================
cat(\"Loading data...\\n\")

# TODO: Replace this with your actual data loading
# mat <- read.table(\"your_data.txt\", header=TRUE, row.names=1)

# Example data
mat <- matrix(rnorm(", n_rows, " * ", n_cols, "), nrow = ", n_rows, ", ncol = ", n_cols, ")
rownames(mat) <- paste0(\"Feature\", 1:", n_rows, ")
colnames(mat) <- paste0(\"Sample\", 1:", n_cols, ")
")

# Add normalization for gene expression
if (data_type == 1) {
    code <- paste0(code, "
# Z-score normalization
mat_scaled <- t(scale(t(mat)))
")
    mat_var <- "mat_scaled"
} else {
    mat_var <- "mat"
}

# Add annotations if requested
if (n_col_anno > 0) {
    code <- paste0(code, "
# ==============================================================================
# 2. CREATE COLUMN ANNOTATIONS
# ==============================================================================
cat(\"Creating column annotations...\\n\")

col_anno <- HeatmapAnnotation(
")
    for (i in 1:n_col_anno) {
        code <- paste0(code, "    Anno", i, " = sample(c(\"A\", \"B\", \"C\"), ", n_cols, ", replace = TRUE),\n")
    }
    code <- paste0(code, "    
    col = list(
")
    for (i in 1:n_col_anno) {
        code <- paste0(code, "        Anno", i, " = c(\"A\" = \"red\", \"B\" = \"blue\", \"C\" = \"green\"),\n")
    }
    code <- paste0(code, "    ),
    annotation_name_side = \"left\"
)
")
}

# Main heatmap code
color_schemes <- c(
    "colorRamp2(c(-2, 0, 2), c(\"blue\", \"white\", \"red\"))",
    "colorRamp2(c(-2, 0, 2), c(\"green\", \"black\", \"red\"))",
    "colorRamp2(seq(min(mat), max(mat), length.out = 100), viridis::viridis(100))",
    "colorRamp2(c(-2, 0, 2), c(\"purple\", \"white\", \"orange\"))"
)

code <- paste0(code, "
# ==============================================================================
# 3. CREATE HEATMAP
# ==============================================================================
cat(\"Creating heatmap...\\n\")

ht <- Heatmap(
    ", mat_var, ",
    name = \"Value\",
    
    # Color
    col = ", color_schemes[color_choice], ",
    
    # Clustering
    cluster_rows = ", toupper(as.character(cluster_rows)), ",
    cluster_columns = ", toupper(as.character(cluster_cols)), ",
    clustering_distance_rows = \"", distance, "\",
    clustering_method_rows = \"", method, "\",
    
    # Display
    show_row_names = ", ifelse(n_rows <= 50, "TRUE", "FALSE"), ",
    show_column_names = TRUE,
    column_names_rot = 45,
")

if (n_col_anno > 0) {
    code <- paste0(code, "    
    # Annotations
    top_annotation = col_anno,
")
}

code <- paste0(code, "    
    # Legend
    heatmap_legend_param = list(
        title_gp = gpar(fontsize = 11, fontface = \"bold\"),
        labels_gp = gpar(fontsize = 9)
    )
)

# ==============================================================================
# 4. SAVE OUTPUT
# ==============================================================================
cat(\"Saving heatmap...\\n\")

pdf(\"", output_name, ".pdf\", width = 10, height = 12)
draw(ht, heatmap_legend_side = \"right\")
dev.off()

png(\"", output_name, ".png\", width = 1200, height = 1400, res = 120)
draw(ht, heatmap_legend_side = \"right\")
dev.off()

cat(\"Done! Files saved:\\n\")
cat(\"  - ", output_name, ".pdf\\n\")
cat(\"  - ", output_name, ".png\\n\")
")

# Write code to file
output_file <- paste0(output_name, "_template.R")
writeLines(code, output_file)

cat("================================================\n")
cat("Template Generated Successfully!\n")
cat("================================================\n")
cat("\nTemplate saved to:", output_file, "\n\n")
cat("Next steps:\n")
cat("  1. Edit the template to load your actual data\n")
cat("  2. Customize colors, annotations, and parameters\n")
cat("  3. Run the template: source('", output_file, "')\n\n")

cat("To generate another template, run this script again.\n")
